### ISSUE TITLE
Устройство в сети но недоступно в HA, при подключении по Type C нет COM порта

### ISSUE THREAD

**Issue by almirus** [SCratORS/SmartIntercom#15]
Добрый день! залили такой 
<details>
  <summary>Конфиг</summary>
  
  ```
substitutions:
  dev_name: smartintercom
  
#ESP8266 Определение нужных GPIO
  base: esp12e
  led_status: GPIO2             # Индикатор статуса API, GPIO2 - это встроенный синий светодиод на ESP12
  led_indicator: GPIO13         # Дополнительный индикатор, который будет показывать режимы и прочее.
  detect_line: GPIO12           # Пин детектора вызова
  button_boot: GPIO0            # Кнопка управления платой и перевода в режим прошивки
  button_ring: GPIO1            # Внешняя кнопка
  relay_line: GPIO14            # Пин "Переключение линии, плата/трубка"
  switch_open: GPIO5            # Пин "Открытие двери"
  switch_phone: GPIO4           # Пин "Трубка положена/поднята"
  
#input_select_mode_value
  input_select_disable: "Не активен"
  input_select_no_answer: "Сброс вызова если нет ответа" 
  input_select_reject: "Сброс вызова"
  input_select_accept: "Открывать всегда"
  
#line_status_text
  line_status_call:   "Вызов"
  line_status_answer: "Ответ"
  line_status_open:   "Открытие двери"
  line_status_reject: "Сброс вызова"
  line_status_close:  "Закрыто"
  
#delay
  call_end_detect_delay: 4000ms     # Интервал между детектированием вызова
  # delay_before_answer: 1000ms       # Отпределили вызов, *** подождали ***... Передаем управление на плату,
                                    # отключаем трубку, *** подождали *** ... воспроизводим аудио, если надо. (Number компонент before_answer)
  delay_before_open_door: 100ms     # Воспроизведение аудио закончилось, *** подождали *** ... нажимаем кнопку открытия двери.
  # delay_open_on_time: 600ms         # Кнопка открытия двери нажата, *** подождали *** ... отпустили кнопку. (Number компонент open_time)
  # delay_after_close_door: 2000ms    # Отпустили кнопку открытия двери, *** подождали *** ... Возвращаем управление на трубку (Number компонент after_close)
  delay_no_answer: 30s              # Пауза для режима "Сброс если нет ответа" - сколько этот ответ плата ждёт

#audio_support
  play_user_access_allowed: playFile(audio_player, "/user_access_allowed.wav")
  play_delivery_access_allowed: playFile(audio_player, "/delivery_access_allowed.wav")
  play_access_denied: playFile(audio_player, "/access_denied.wav")
  play_user_no_connect: playFile(audio_player, "/user_no_connect.wav")
  play_user_no_answer: playFile(audio_player, "/user_no_answer.wav")

# Логика работы:
# 
# Определение "Вызова", интеревал между детектированием - call_end_detect_delay (3 сек.)
# Включение LED индикатора в режим быстрого мигания.
#
# +-----------Если включен режим MUTE-----------+ Это позволяет при вызове быстро передать управление
# | Включение на плате режима "трубка положена" | на плату, и трубка не успевает издать звук вызова.
# | Переключение управления на плату            | При этом на плате устанавливается режим положеной
# +---------------------------------------------+ трубки, поэтому на блоке вызова просто идет вызов.
#
# delay_before_switch_line: (1000 мсек.)          Ждем, чтобы "желательно" попасть в паузу между
#                                                 вызовными сигналами, заодно чтобы блок вызова
#                                                 успел перейти в режим работы с абонентом, - малоли.
#
# +---Если режим "сброс, если нет ответа"-------+ Если установлен этот режим, то просто ждем 30 сек.
# | delay_no_answer (30 сек)                    | и запускаем скрипт сброса звонка.
# | Включение режима "сброс"                    |
# +---------------------------------------------+        
#
# +---Если включен какой-нибудь режим работы----+ Если выбран какой-либо режим кроме "Неактивен",
# | Переключение управления на плату            | то начинаем работу по отработке вызова.
# | "Поднимаем трубку"                          | Делаем поднятие трубки, малоли был режим мьюта.
# | delay_before_voice (1000 мсек.)             | Ждем, чтобы блок вызова успел отработать поднятие
# |                                             | трубки, и дать работу с аудио трактом.
# | +--Если режим курьера или аудио включено--+ | Если режим курьера или включено аудио сообщение,
# | | Воспроизведение аудио                   | | то собственно воспроизводим аудио, и ждем окончания
# | +-----------------------------------------+ | воспроизведения
# |                                             |
# | +--Если открывающий режим-----------------+ | Открывающий режим - разовый/постоянный или "курьер"
# | | delay_before_open_door (100 мсек.)      | | Ждем немного, чтобы с аудио, которое воспроизводилось
# | | Нажатие кнопки открытия двери.          | | на блоке вызова не обрывало. И жмём "Открыть"
# | +-----------------------------------------+ |
# |                                             | 
# | delay_open_on_time (600 мсек.)              | Ждем, чтобы блок вызова успел переварить сигналы.
# | Отпускание кнопки открытия двери.           | Отпускаем кнопку открытия, если не была нажата - 
# | delay_after_close_door (2000 мсек.)         | ну и пофиг. Ждем, перед сбросом. Если не ждать, 
# | Переключаем линию назад на трубку           | то может детектор отработать еще раз, и будет 
# +---------------------------------------------+ по кругу гонять, пока на блоке вызова сброс не нажмут.
#                                                 Переключаем линию на трубку, а она у нас положена,
#                                                 и поэтому блок вызова отпеределяет это как
#                                                 положили трубку и завершает сеанс вызова.
#
# Ожидание окончания связи с блоком вызова          
# Выключение режима "положенной трубки"          Выключение GPIO, чтобы энергию не кушал,
# Переключение линии назад на трубку             а физическая трубка положена, и она будет на линии.
# Выключение LED индикатора
uart:
  id: uart10
  tx_pin: GPIO16
  rx_pin: GPIO2
  baud_rate: 256000
  stop_bits: 1

esp8266:
  board: ${base}
  restore_from_flash: true

esphome:
  name: ${dev_name}
  comment: "Перед прошивкой проверь наличие настроек wifi_ssid и wifi_password в файле \"SECRETS\" - кнопка вверху справа"
  libraries:
    - SPI
    - ESP8266SdFat
    - SDFS
    - SD
    - ESP8266WiFi
    - LittleFS
    - I2S
    - https://github.com/SCratORS/FTPClientServer
    - ESP8266Audio
  includes:
    - lib/ESPUtils.h
    - lib/ESPAudio.h
  platformio_options:
      board_build.f_cpu: 160000000L
      board_build.filesystem: littlefs
      board_build.ldscript: eagle.flash.4m2m.ld   
#      build_flags: 
#        - "-DSDCARD" # Поддержка SD карты 

  on_boot:
    priority: -100
    then:
      - script.execute: boot_script
 
# Настройки Вай-Фая тащим из файла секретов, или вписывай руками  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

# Включаем доступ к каптиву - это для подключения к домашнему Вай-Фаю через Веб-морду 
captive_portal:

# Включаем дефолтное логирование. 
logger:
  baud_rate: 0

# Постоянная Веб-морда
#web_server:
#  local: true # Запрет доступа из внешней сети

# Глобальные переменные
globals:
  - id: current_mode
    type: int
    initial_value: '0'
    restore_value: true
  - id: status_line
    type: bool
    initial_value: 'false'
  - id: status_mute
    type: bool
    initial_value: 'false'
    restore_value: true
  - id: status_phone_disable
    type: bool
    initial_value: 'false'
    restore_value: true
  - id: status_leding
    type: bool
    initial_value: 'true'
    restore_value: true
  - id: status_sound
    type: bool
    initial_value: 'true'
    restore_value: true
  - id: status_once_mode
    type: int
    initial_value: '0'
    restore_value: true


# MQTT и API вместе работать не могут. Выбери что надо.
# +---------------------------------------------+
# Активируем работу по протоколу MQTT    
# +---------------------------------------------+
#mqtt:
  #broker: 192.168.0.254
  #username: "mqtt-client"
  #password: "j3qq4h7h2v2hch4m3hk86m8vw" 
# +---------------------------------------------+
# Активируем работу с API HomeAssistans через интеграцию ESPHome
# +---------------------------------------------+
api:
# +---------------------------------------------+

# Возможность обновляться по воздуху
ota:
  password: "12345678"

custom_component:
  - id: ftp_server
    lambda: 'return {new FTPSrv("","")};' # (Логин, Пароль). По умолчанию anonymous  
  - id: audio_player
    lambda: 'return {new ESPAudio()};'
  - id: updater
    lambda: 'return {new FirmwareUpdate()};'
ld2410:
# Пошла мазута
light:
  - platform: status_led
    id: led_status
    internal: true
    pin:
      number: $led_status
      inverted: True
    effects:
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 1900ms
  - platform: monochromatic
    id: led_action
    output: indicator
    internal: true
    restore_mode: ALWAYS_OFF
    default_transition_length: 0ms
    effects:
      - pulse:
          name: pulse
          update_interval: 2s
      - strobe:
          name: blink
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 1900ms
      - strobe:
          name: calling
          colors:
            - state: true
              duration: 50ms
            - state: false
              duration: 50ms

script:
  - id: boot_script
    then:
      - logger.log: "Boot config"
      - if:
          condition:
            lambda: 'return id(current_mode) == 0;'
          then:
            - select.set:
                id: mode_select
                option: ${input_select_disable}
            - logger.log: ${input_select_disable}
          else:      
            if:
              condition:
                lambda: 'return id(current_mode) == 1;'
              then:
                - select.set:
                    id: mode_select
                    option: ${input_select_no_answer}
                - logger.log: ${input_select_no_answer}
              else:
                if:
                  condition:
                    lambda: 'return id(current_mode) == 2;'
                  then:
                    - select.set:
                        id: mode_select
                        option: ${input_select_reject}
                    - logger.log: ${input_select_reject}
                  else:   
                    - select.set:
                        id: mode_select
                        option: ${input_select_accept}
                    - logger.log: ${input_select_accept}
      - if:
          condition:
            lambda: 'return id(status_leding);'
          then:
            switch.turn_on: led
      - if:
          condition:
            lambda: 'return id(status_sound);'
          then:
            switch.turn_on: sound
      - if:
          condition:
            lambda: 'return id(status_mute);'
          then:
            switch.turn_on: mute
      - if:
          condition:
            lambda: 'return id(status_phone_disable);'
          then:
            switch.turn_on: phone_disable
      - if:
          condition:
            lambda: 'return id(status_once_mode) == 1;'
          then:
            switch.turn_on: accept_call
          else:
            if:
              condition:
                lambda: 'return id(status_once_mode) == 2;' 
              then:
                switch.turn_on: delivery
              else:
                if:
                  condition:
                    lambda: 'return id(status_once_mode) == 3;'
                  then:
                    switch.turn_on: reject_call
  - id: led_check
    then:
      - light.turn_off:
          id: led_action
      - light.turn_off:
          id: led_status
      - if:
          condition:
            lambda: 'return id(status_leding);'
          then:
          - if:
              condition:
                lambda: 'return id(status_mute);'
              then:
                light.turn_on:
                  id: led_action
                  effect: pulse
          - if:
              condition:
                  lambda: 'return id(status_once_mode) > 0;'
              then:
                if:
                  condition:
                    lambda: 'return id(status_once_mode) < 3;'
                  then:
                    light.turn_on:
                      id: led_action
                      effect: blink
                  else:
                    light.turn_on:
                      id: led_status
                      effect: blink
          - if:
              condition:
                lambda: 'return id(status_line);'
              then:
                light.turn_on:
                  id: led_action
                  effect: calling

  # Accept incoming call
  - id: accepting
    then:
      if:
        condition:
          lambda: 'return id(status_line);'
        then:
          - output.turn_on: relay_switch_line
          - output.turn_off: phone_down
          - lambda: 'id(line_status).publish_state("${line_status_answer}");'
          - delay: !lambda "return id(delay_before_answer).state;"
          - if:
              condition:
                switch.is_on: delivery
              then:
                lambda: ${play_delivery_access_allowed};
              else:
                if:
                  condition:
                    lambda: 'return id(status_sound);'
                  then:
                    lambda: ${play_user_access_allowed};                   
          - wait_until:
              lambda: 'return !isPlaying(audio_player);'
          - delay: $delay_before_open_door
          - output.turn_on: open_door
          - lambda: 'id(line_status).publish_state("${line_status_open}");'
          - delay: !lambda "return id(delay_open_time).state;"
          - output.turn_off: open_door
          - lambda: 'id(line_status).publish_state("${line_status_reject}");'
          - delay: !lambda "return id(delay_after_close).state;"
          - if:
              condition:
                lambda: 'return id(status_line);'
              then:
                output.turn_on: phone_down
          - lambda: 'id(line_status).publish_state("${line_status_close}");'
          - if:
              condition:
                switch.is_on: accept_call
              then:
                - switch.turn_off: accept_call
                - switch.turn_off: delivery

  # Reject incoming call
  - id: rejecting
    then:
      if:
        condition:
          lambda: 'return id(status_line);'
        then:
          - output.turn_on: relay_switch_line
          - output.turn_off: phone_down
          - lambda: 'id(line_status).publish_state("${line_status_answer}");'
          - delay: !lambda "return id(delay_before_answer).state;"
          - if:
              condition:
                lambda: 'return id(status_sound);'
              then:
                if:
                  condition:
                    lambda: 'return id(current_mode) == 2;'
                  then:
                    lambda: ${play_access_denied};                  
                  else:
                    if:
                      condition:
                        switch.is_on: reject_call
                      then:
                        lambda: ${play_user_no_connect};                 
                      else:
                        lambda: ${play_user_no_answer};
          - wait_until:
              lambda: 'return !isPlaying(audio_player);'
          - delay: !lambda "return id(delay_open_time).state;"
          - lambda: 'id(line_status).publish_state("${line_status_reject}");'
          - if:
              condition:
                lambda: 'return id(status_line);'
              then:
                output.turn_on: phone_down
          - lambda: 'id(line_status).publish_state("${line_status_close}");'
          - delay: !lambda "return id(delay_after_close).state;"
          - if:
              condition:
                switch.is_on: reject_call
              then:
                switch.turn_off: reject_call

  # Reject no answer
  - id: rejecting_no_answer
    then:
      if:
        condition:
          lambda: 'return id(status_line);'
        then:
          - delay: $delay_no_answer
          - script.execute: rejecting

  - id: state_call
    then:
      if:
        condition:
          switch.is_on: accept_call
        then:
          script.execute: accepting
        else:
          if:
            condition:
              switch.is_on: reject_call
            then:
              script.execute: rejecting
            else:
              if:
                condition:
                  lambda: 'return id(current_mode) == 3;'
                then:
                  script.execute: accepting
                else:
                  if:
                    condition:
                      lambda: 'return id(current_mode) == 2;'
                    then:
                      script.execute: rejecting
                    else:
                      if:
                        condition:
                          lambda: 'return id(current_mode) == 1;'
                        then:
                          script.execute: rejecting_no_answer
                        else:
                          lambda: 'id(line_status).publish_state("${line_status_close}");'


number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
  - platform: template
    name: ${dev_name}_before_answer
    icon: "mdi:clock"
    id: delay_before_answer
    optimistic: true
    mode: box
    unit_of_measurement: "мс"
    entity_category: "config"
    restore_value: true
    initial_value: 1000
    min_value: 100
    max_value: 5000
    step: 100
  - platform: template
    name: ${dev_name}_open_time
    icon: "mdi:clock"
    id: delay_open_time
    optimistic: true
    mode: box
    unit_of_measurement: "мс"
    entity_category: "config"
    restore_value: true
    initial_value: 600
    min_value: 100
    max_value: 2000
    step: 50
  - platform: template
    name: ${dev_name}_after_close
    icon: "mdi:clock"
    id: delay_after_close
    optimistic: true
    mode: box
    unit_of_measurement: "мс"
    entity_category: "config"
    restore_value: true
    initial_value: 2000
    min_value: 100
    max_value: 5000
    step: 100

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level 
  - platform: template
    name: ${dev_name}_modes
    icon: "mdi:deskphone"
    optimistic: true
    id: mode_select
    options:
      - ${input_select_disable}
      - ${input_select_no_answer}
      - ${input_select_reject}
      - ${input_select_accept}
    initial_option: ${input_select_disable}
    on_value:
      lambda: |-
          if (id(mode_select).state == "${input_select_disable}") {
            id(current_mode) = 0;
          } else if (id(mode_select).state == "${input_select_no_answer}") {
            id(current_mode) = 1;
          } else if (id(mode_select).state == "${input_select_reject}") {
            id(current_mode) = 2;
          } else {
            id(current_mode) = 3;
          }
          
text_sensor:
  - platform: template
    id: line_status
    icon: "mdi:bell"
    name: ${dev_name}_line_status
    lambda: 'return {"${line_status_close}"};'
  - platform: wifi_info
    ip_address:
      name: ${dev_name}_ip
      icon: "mdi:lan"
    ssid:
      name: ${dev_name}_ssid
      icon: "mdi:wifi"
    mac_address:
      name: ${dev_name}_mac
      icon: "mdi:lan"
  - platform: custom
    lambda: |-
      auto fs_info_sensor_ = new FSInfoSensor();
      App.register_component(fs_info_sensor_);
      return {fs_info_sensor_->firmware_current_version, fs_info_sensor_->fs_info_sensor};
    text_sensors:
      - name: ${dev_name}_firmware
        icon: "mdi:information"
        entity_category: diagnostic
      - name: ${dev_name}_fs_used
        icon: "mdi:micro-sd"
        entity_category: diagnostic


sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
  - platform: wifi_signal
    name: ${dev_name}_rssi
    update_interval: 600s
    
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    id: line_detect
    name: ${dev_name}_line_detect
    pin:
      number: $detect_line
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: ${call_end_detect_delay}
    on_press:
      if:
        condition:
          lambda: 'return id(status_line) == false;'
        then:
          - lambda: 'id(status_line) = true;'
          - script.execute: led_check
          - logger.log: "Incoming call detected"
          - if:
              condition:
                lambda: 'return id(status_mute);'
              then:
                - output.turn_on: phone_down
                - output.turn_on: relay_switch_line
          - delay: !lambda "return id(delay_before_answer).state;"
          - script.execute: state_call
    on_release:
      - if:
          condition:
            switch.is_on: phone_disable
          then:
            - output.turn_on: phone_down
            - output.turn_on: relay_switch_line
          else:
            - output.turn_off: phone_down
            - output.turn_off: relay_switch_line
      - lambda: 'id(status_line) = false;'
      - logger.log: "Incoming call completed"
      - script.execute: led_check
    on_state:
      lambda: |-
        if (x) {
          id(line_status).publish_state("${line_status_call}");
        } else {
          id(line_status).publish_state("${line_status_close}");
        }   
        
  - platform: gpio
    id: ${dev_name}_button
    pin:
      number: $button_boot
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        switch.toggle: accept_call
    on_multi_click:
      - timing:
        - ON for at least 5s
        then:
          lambda: |-
            ESP_LOGW("DMF", "Erase settings and restart...");
            wifi::global_wifi_component->save_wifi_sta("-----", "");
            delay(500);
            ESP.restart();

  - platform: gpio
    id: ${dev_name}_external_button
    name: ${dev_name}_external_button
    pin:
      number: $button_ring
      mode: INPUT_PULLUP
      inverted: True

output:
  - platform: gpio
    id: relay_switch_line
    pin:
      number: $relay_line
      mode: OUTPUT
  - platform: gpio
    id: open_door
    pin:
      number: $switch_open
      mode: OUTPUT
  - platform: esp8266_pwm
    id: indicator
    pin:
      number: $led_indicator
      mode: OUTPUT
  - platform: gpio
    id: phone_down
    pin:
      number: $switch_phone
      mode: OUTPUT

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
  - platform: restart
    name: ${dev_name}_restart
  - platform: template
    name: ${dev_name}_save
    id: save
    icon: "mdi:content-save-cog"
    entity_category: "config"
    on_press:
      - lambda: 'global_preferences->sync();'
  - platform: template
    name: ${dev_name}_update
    icon: "mdi:arrow-up-bold-circle"
    entity_category: "diagnostic"
    on_press:
      - lambda: 'startUpdate(updater);'  

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
  - platform: template
    name: ${dev_name}_delivery
    id: delivery
    icon: "mdi:package"
    turn_on_action:
      - switch.template.publish:
          id: delivery
          state: true
      - switch.turn_on: accept_call
    turn_off_action:
      - switch.template.publish:
          id: delivery
          state: false
      - if:
          condition:
            switch.is_on: accept_call
          then:
            lambda: 'id(status_once_mode) = 1;'
          else:
            lambda: 'id(status_once_mode) = 0;'
      - script.execute: led_check
          

  - platform: template
    name: ${dev_name}_accept_call
    id: accept_call
    icon: "mdi:door-open"
    turn_on_action:
      - switch.template.publish:
          id: accept_call
          state: true
      - switch.turn_off: reject_call
      - logger.log: "Accept call switch is ON"
      - if:
          condition:
            switch.is_on: delivery
          then:
            lambda: 'id(status_once_mode) = 2;'
          else: 
            lambda: 'id(status_once_mode) = 1;'
      - script.execute: led_check
      - if:
          condition:
            lambda: 'return id(status_line);'
          then:
            - logger.log: "Execute action script"
            - script.execute: state_call
          else:
            - logger.log: "No incoming call. One-time mode is set."
    turn_off_action:
      - switch.template.publish:
          id: accept_call
          state: false
      - switch.turn_off: delivery
      - lambda: 'id(status_once_mode) = 0;'
      - script.execute: led_check

    
  - platform: template
    name: ${dev_name}_reject_call
    id: reject_call
    icon: "mdi:phone-hangup"
    turn_on_action:
      - switch.template.publish:
          id: reject_call
          state: true
      - switch.turn_off: accept_call
      - switch.turn_off: delivery
      - lambda: 'id(status_once_mode) = 3;'
      - script.execute: led_check
      - if:
          condition:
            lambda: 'return id(status_line);'
          then:
            - logger.log: "Execute action script"   
            - script.execute: state_call
          else:
            - logger.log: "No incoming call. One-time mode is set."
    turn_off_action:
      - switch.template.publish:
          id: reject_call
          state: false
      - lambda: 'id(status_once_mode) = 0;'
      - script.execute: led_check

  - platform: template
    name: ${dev_name}_mute
    id: mute
    icon: "mdi:bell-off"
    entity_category: "config"
    turn_on_action:
      - switch.template.publish:
          id: mute
          state: true
      - lambda: 'id(status_mute) = true;'
      - script.execute: led_check
    turn_off_action:
      - switch.template.publish:
          id: mute
          state: false
      - lambda: 'id(status_mute) = false;'
      - script.execute: led_check
              
  - platform: template
    name: ${dev_name}_phone_disable
    id: phone_disable
    icon: "mdi:phone-off"
    entity_category: "config"
    turn_on_action:
      - switch.template.publish:
          id: phone_disable
          state: true
      - lambda: 'id(status_phone_disable) = true;'
      - if:
          condition:
            lambda: 'return id(status_line) == false;'
          then:
            - output.turn_on: phone_down
            - output.turn_on: relay_switch_line
    turn_off_action:
      - switch.template.publish:
          id: phone_disable
          state: false
      - lambda: 'id(status_phone_disable) = false;'
      - if:
          condition:
            lambda: 'return id(status_line) == false;'
          then:
            - output.turn_off: phone_down
            - output.turn_off: relay_switch_line   
            
  - platform: template
    name: ${dev_name}_led
    id: led
    icon: "mdi:led-on"
    entity_category: "config"
    turn_on_action:
      - switch.template.publish:
          id: led
          state: true
      - lambda: 'id(status_leding) = true;'
      - script.execute: led_check
    turn_off_action:
      - switch.template.publish:
          id: led
          state: false
      - lambda: 'id(status_leding) = false;'
      - script.execute: led_check

  - platform: template
    name: ${dev_name}_sound
    id: sound
    icon: "mdi:volume-high"
    entity_category: "config"
    turn_on_action:
      - switch.template.publish:
          id: sound
          state: true
      - lambda: 'id(status_sound) = true;'
    turn_off_action:
      - switch.template.publish:
          id: sound
          state: false
      - lambda: 'id(status_sound) = false;'

  ```
  
</details>

к стандартному конфигу добавил UART 
uart:
  id: uart10
  tx_pin: GPIO16
  rx_pin: GPIO2
  baud_rate: 256000
  stop_bits: 1
поддержку сенсора ld2410
подпаялся к этим ножкам и залил прошивку. После этого устройство отвалилось из сети. Залить по воздуху невозможно - HA его не видит. По кабелю COM порт не появлсяется.
само устройство в сети, по IP напрямую не открывается
![image](https://github.com/SCratORS/SmartIntercom/assets/16898685/eb91f73c-4186-4127-b19e-31f2c61211ac)

как восстановить?
