### ISSUE TITLE
MQTT шаблон для Sprut.hub

### ISSUE THREAD

**Issue by MaximSidorov777** [SCratORS/SmartIntercom#17]
Тестировалось на плате [Smartintercom Nelma 4](http://shop.scrators.ru/index.php?route=product/product&language=ru-ru…) (rev. 4E, ESP32, ESPHome) Ext.

Сначала включаем протокол MQTT, для этого в конфиге [smartintercom-esp32.yaml](https://github.com/SCratORS/SmartIntercom/blob/main/ESPHome/smartintercom-esp32.yaml) ([113 строчка](https://github.com/SCratORS/SmartIntercom/blob/d49d9c9b54235692ecd0d4b0ec75d9a81ae2238c/ESPHome/smartintercom-esp32.yaml#L113)) прописываем следующее:

```
mqtt:
  broker: "IP"
  port: "44444"
  username: ""
  password: ""
  # Необязательно
  client_id: "domofon"
  # Отключаем discovery для HA
  discovery: false
  # Меняем префикс для удобства (необязательно)
  topic_prefix: "domofon"
```

- **broker** — IP-адрес Sprut.hub'a;
- **port** — порт брокера из настроек MQTT-контроллера Sprut.hub'a;
- **username** — имя пользователя;
- **password** — пароль;
- **client_id** — айди клиента с которым плата будет коннектится к брокеру (необязательно);
- **discovery** — отключаем discovery-режим для HomeAssistant, нужен для работы по MQTT с HomeAssistant;
- **topic_prefix** — под каким префиксом в брокере будут отображаться сообщения платы (необязательно, для удобства);

Также не забываем отключить API-компонент ESPHome ([120 строчка](https://github.com/SCratORS/SmartIntercom/blob/d49d9c9b54235692ecd0d4b0ec75d9a81ae2238c/ESPHome/smartintercom-esp32.yaml#L120)):
`#api:`

Далее в соответствии с [инструкцией](https://wiki.spruthub.ru/Добавление_кастомных_шаблонов_для_любых_устройств) добавляем шаблон [SCHome_Smartintercom_v2.5.json](https://github.com/SCratORS/SmartIntercom/files/15210835/SCHome_Smartintercom_v2.5.json) в Sprut.hub.

После перезагрузки MQTT-контроллера в Sprut.hub у вас появится устройство «Домофон».

<img width="500" alt="Снимок экрана 2024-05-04 в 22 35 51" src="https://github.com/SCratORS/SmartIntercom/assets/86353917/83b8255d-3783-458e-904c-081e317f5a39">
<img width="500" alt="Снимок экрана 2024-05-04 в 22 36 48" src="https://github.com/SCratORS/SmartIntercom/assets/86353917/27304620-d4a4-43ee-8c9c-a8211c7da23b">
<img width="500" alt="Снимок экрана 2024-05-04 в 22 36 38" src="https://github.com/SCratORS/SmartIntercom/assets/86353917/b3aa7f5e-4b96-4fd4-a09c-4317c196cd48">
