### ISSUE TITLE
Мануал. Делаем управление домофоном через телеграм

### ISSUE THREAD

**Issue by DivanX10** [SCratORS/SmartIntercom#3]
**Внешний вид клавиатуры**
![image](https://user-images.githubusercontent.com/64090632/133158586-6e201ead-f1a2-4ad2-8daa-3950e6445361.png)

**Создадим автоматизацию**.
Создайте например файлик с таким именем domofon_control_telegram.yaml и вставьте код ниже. Сам файлик domofon_control_telegram.yaml закидываем в automation old, это автоматизация через yaml. У меня  настроено так  automation old: !include_dir_merge_list includes/automation

```
- alias: 'Телеграм: Домофон. Управление'
  description: Управление домофоном через телеграм
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/domofon'' }}'
      sequence:
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: &msg |
            {{'\U00002699'}} **Режим работы домофона**
#Клавиатура
          inline_keyboard: &keyb
          - '{% set domofon_modes = states("input_select.smart_domofon_scrators_modes") %}
             {% if domofon_modes == "Не активен" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Не активен:/domofon_not_active,
             {% set domofon_modes = states("input_select.smart_domofon_scrators_modes") %}
             {% if domofon_modes == "Открывать всегда" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Открывать всегда:/domofon_open_always'
          - '{% if is_state("switch.smart_domofon_scrators_mute", "on") %} {{"🟢"}}
             {% else %} {{"🔴"}} 
             {% endif %}
             Беззвучный режим:/domofon_mute,
             {% set domofon_modes = states("input_select.smart_domofon_scrators_modes") %}
             {% if domofon_modes == "Сброс вызова" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Сброс вызова:/domofon_reset_call'
          - '{% set domofon_modes = states("input_select.smart_domofon_scrators_modes") %}
             {% if domofon_modes == "Сброс вызова если нет ответа" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Сброс вызова если нет ответа:/domofon_resetting_call_no_response'
          - Назад:/backhome

#Кнопка №1. Не активен
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_not_active" }}'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.smart_domofon_scrators_modes
        data:
          option: Не активен
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №2. Открывать всегда
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_open_always" }}'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.smart_domofon_scrators_modes
        data:
          option: Открывать всегда
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №3. Беззвучный режим
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_mute" }}'
      sequence:
      - service: switch.toggle
        target:
          entity_id: switch.smart_domofon_scrators_mute
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №4. Сброс вызова
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_reset_call" }}'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.smart_domofon_scrators_modes
        data:
          option: Сброс вызова
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №5. Сброс вызова если нет ответа
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_resetting_call_no_response" }}'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.smart_domofon_scrators_modes
        data:
          option: Сброс вызова если нет ответа
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb
    default: []
  mode: restart

```
