### ISSUE TITLE
Автоматическое отключение однократного открытия домофона

### ISSUE THREAD

**Issue by xakepShilo** [SCratORS/SmartIntercom#8]
Иногда бывает подал команду открыть домофон и забыл отменить. Потому небольшая автоматизация для людей с некоторым количеством склероза - как я например. 

Создаем таймер:
```
smartintercom_wait:
  name: 'Домофон автовыключение открытия'
  duration: '00:10:00'
```
... естественно, что время автоматического выключения можете сделать свое. В примере 10 минут.

Далее создаем три автоматизации:
```
automation:
  - id: 'smartintercom_accept_call_on'
    alias: Домофон (включается accept_call)
    description: ''
    trigger:
    - platform: state
      entity_id: switch.smartintercom_accept_call
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: timer.start
      entity_id: timer.smartintercom_wait
    mode: single

  - id: 'smartintercom_accept_call_off'
    alias: Домофон (выключается accept_call)
    description: ''
    trigger:
    - platform: state
      entity_id: switch.smartintercom_accept_call
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: timer.cancel
      entity_id: timer.smartintercom_wait
    mode: single

  - id: 'smartintercom_timer_finished'
    alias: Домофон (обработчик таймера accept_call)
    description: ''
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.smartintercom_wait
    condition:
    - condition: state
      entity_id: switch.smartintercom_accept_call
      state: 'on'
    action:
    - service: switch.turn_off
      target:
        entity_id: switch.smartintercom_accept_call
    mode: single
```
Первая "smartintercom_accept_call_on" - запускает созданный выше таймер при открытии домофона.
Вторая "smartintercom_accept_call_off" - останавливает запущенный таймер при отключении однократного открытия домофона.
И третья "'smartintercom_timer_finished" - ни что иное, как обработчик таймера. Который по истечении времени так же отключит однократное открытие.

Перегружаем в Home Assistant автоматизации и таймеры и склероз побежден. :))
